### ISSUE TITLE
Update collegian pages links to collegian.xyz

### ISSUE THREAD

**Issue by stephenermshar** [ASWWU-Web/shared-ng#29]
Since collegian is now managing all articles on collegian.xyz, any links that point to the collegian pages directory or sub-site should now point to collegian.xyz.

Currently the departments drop-down still points to the collegian directory in pages. Though there may be other references in the site. 

It may be good to create a general static collegian info page since all departments have one, but for now all links go to collegian.xyz

**Comment by octagonprogramming** [comment]
tested and deployed
