### ISSUE TITLE
Add departments to navbar drop-down menu

### ISSUE THREAD

**Issue by lucasmarcondes** [ASWWU-Web/shared-ng#34]
## New, Black Navbar

* Add Mountain Rents
![image](https://user-images.githubusercontent.com/26172645/67535964-c7875b80-f689-11e9-8071-f463737fd32b.png)

**Comment by stephenermshar** [comment]
@octagonprogramming Work on this from the homepage project in the frontend repo, then commit to the shared-ng repo from there

**Comment by stephenermshar** [comment]
Looks like this was merged and deployed already, closing the issue.
